node {

    def imageTag = "peterngtr/rest-demo:${env.BUILD_NUMBER}"
    def dockerHome = tool 'myDocker'

    stage("Initializing") {
        cleanWs();
        checkout scm;
        bat 'git reset --hard'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }

    stage("Building Images") {
        bat "docker build -t ${imageTag} -f docker/Dockerfile ."
    }

    stage("Running Tests") {
        try {
            bat "jenkins/run-tests.bat ${env.BUILD_NUMBER}"
        }
        finally {
            bat "ls report/"
            allure includeProperties: false, jdk: '', results: [[path: 'report']]
        }
    }


}